citycash_poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    # /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    # /polls/5/vote/
    path('<str:question_id>/vote/', views.vote, name='vote'),

    path('search', views.QuestionSearchListView.as_view(), name='question_search_list_view'),

    path('api/data', views.get_data, name='api-data'),
    path('api/chart/data/<int:question_id>', views.ChartData.as_view()),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_data'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# Testing Many to Many

class Publication(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

class Article(models.Model):
    headline = models.CharField(max_length=100)
    publications = models.ManyToManyField(Publication)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ('headline',)


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=30)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    population = models.PositiveIntegerField()

    def __str__(self):
        return self.name

polls/views.py
#2480678656
#12/2/2000

import os
import operator

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Question, Choice
from django.db.models import Sum, Count
from django.http import JsonResponse

from rest_framework.views import APIView
from rest_framework.response import Response

from django.contrib.auth import get_user_model

# Create your views here.

class IndexView(generic.ListView):

    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    queryset = Choice.objects.values('question_id','question__question_text','question__pub_date').annotate(Sum('votes'), total=Count('question_id')).filter(total__gte=2)
    paginate_by = 3

    # def get_context_data(self, **kwargs):
    #     # Call the base implementation first to get a context
    #     context = super(IndexView, self).get_context_data(**kwargs)
    #     # Add in the publisher
    #     # context['latest_question_list'] = Question.objects.order_by('-pub_date')[:5]
    #     # Choice.objects.annotate(num_books=Sum('votes'))
    #     # print(context)
    #     context.update({'question_with_votes': [(Question.objects.get(pk=each['question']).qu,each['votes']) for each in Choice.objects.values('question').annotate(votes=Sum('votes'))]})
    #     # context['votes'] = Choice.objects.all().filter(question=)
    #     print(context)
    #     return context


    # def get_queryset(self):
    #     # context_object_name = {'latest_question_list':Choice.objects.values('question').annotate(votes=Sum('votes'))}
    #     # questions = Choice.objects.values('question_id','question__question_text','question__pub_date').annotate(Sum('votes'))[:5]
    #     # paginator = Paginator(questions, 3) # < 3 is the number of items on each page
    #     # page = request.Get.get('page') # < Get the page number
    #     #
    #     # questions = paginator.get_page(page) # < New in 2.0
    #     #
    #     # return questions;
    #     return Choice.objects.values('question_id','question__question_text','question__pub_date').annotate(Sum('votes'))

class QuestionSearchListView(generic.ListView):
    paginate_by = 3
    def get_queryset(self):
        result = super(QuestionSearchListView, self).get_queryset()
        return result

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     #output = ', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(template.render(context, request))
#     # a shortcut render
#     return render(request, 'polls/index.html', context)



def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    print("===========",question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def get_data(request, *args, **kwargs):
    data = {
        "sales": 100,
        "customers": 10,
    }
    return JsonResponse(data) # http response

User = get_user_model()

class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None, question_id = False):
        id = question_id
        print(id)
        qs_count = Choice.objects.filter(question_id=id)
        labels = []
        default_items = []
        for c in qs_count:
            i=0;
            labels.insert(i, c.choice_text)
            default_items.insert(i, c.votes)
            i = i + 1;

        data = {
                "labels": labels,
                "default": default_items,
        }
        return Response(data)


class HomeView(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request, 'polls/chart.html', {"customers": 10})

polls/templates/base/bootstrap_defaults.html
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

polls/templates/base/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

polls/templates/base/js.html
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Citycash Poll</title>{% endblock %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/poll.css' %}">

    <!-- Google Font css-->
    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto" rel="stylesheet">

    <!-- Font Awesome css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54botsOGbiDQ" crossorigin="anonymous"> -->

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


</head>
<body>
    <div class="header">
        <a href="{% url 'polls:index' %}" class="logo">Poll App</a>
    </div>
    {% block content %}{% endblock %}

        <footer>
            <p>Find question rating answer</p>
            <small>🕷<a href="{% url 'polls:index' %}">Poll App </a>.</small>
        </footer>

     <!-- js library -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block title %}
    <title>Voting Question</title>
{% endblock %}

{% block content %}

    {% if error_message %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-right: 10%; margin-left: 10%;" role="alert">
            <strong>{{ error_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

     <div class="question_text">
         <p class="question_view">{{ question.question_text }}</p>
     </div>

 <div class="question_text">
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <div class="custom-control custom-radio" style="margin-top: 5px;">
                <input type="radio" class="custom-control-input" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                <label  class="custom-control-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            </div>
        {% endfor %}
        <input type="submit" value="Vote" class="btn btn-dark" style="margin-top: 10px;">
    </form>
 </div>

{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block title %}
    <title>Citycash Poll</title>
{% endblock %}

{% block content %}
    {% if latest_question_list %}

            <form class="input-group md-form form-sm form-2 pl-0 question_text" style="width: 80% !important;" id="searchform" action="{% url 'polls:question_search_list_view' %}" method="get" accept-charset="utf-8">
                <input class="form-control my-0 py-1 red-border" id="searchbox" name="q" type="text" placeholder="Search" aria-label="Search" style="margin-left: 2%;">
                <div class="input-group-append">
                    <button type="submit" class="input-group-text red lighten-3"><i class="fa fa-search text-grey" aria-hidden="true"></i></button>
                </div>
            </form>

        {% for question in latest_question_list %}
            <div class="question_text">
                <a href="{% url 'polls:detail' question.question_id %}" style="text-decoration: none !important;">{{ question.question__question_text }}</a>
                <div class="question_info">
                    <div class="info_left">
                        <span><i class="fa fa-heart" style="color: red !important;margin-right: 2px;"></i>{{ question.votes__sum }}</span>
                    </div>
                    <div class="info_right">
                        <span style="text-align: right"><i class="fa fa-clock-o" style="color: #7c8faa !important;margin-right: 2px;"></i>{{ question.question__pub_date }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% if is_paginated %}

          <ul class="pagination" style="margin-top: 15px;margin-right: 10% !important;float: right !important;>
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" style="color: black;">Previous</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">Previous</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="page-item active"><span class="page-link" style="color: black;cursor: text;">{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}" style="color: black;">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" style="color: black;" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">Next</span></li>
            {% endif %}
          </ul>

        {% endif %}

    {% else %}
        <div class="question_text">
            <p>No polls are available.</p>
        </div>
    {% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block title %}
    <title>Result Question</title>
{% endblock %}

{% block content %}

    {% include 'base/css.html' %}
    {% include 'base/bootstrap_defaults.html' %}
    {% include 'base/js.html' %}

    <script>
    var qid = {{ object.id }};
    console.log(qid);
        var endpoint = '/polls/api/chart/data/'+qid;
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})

function setChart(){
    var ctx2 = document.getElementById("myChart");
    var myChart = new Chart(ctx2, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

}


    </script>

    <div class="question_text">
         <p class="question_view">{{ object.question_text }}</p>
     </div>
    <div class="question_text">

        <div class='row'>
            <div class='col-sm-12' url-endpoint='{% url "polls:api-data" %}'>
                <div class='col-sm-6'>
                   <ul>
                        {% for choice in object.choice_set.all %}
                            <li>{{ choice.choice_text }}</li> {{ choice.votes }} vote{{ choice.votes|pluralize }}
                        {% endfor %}
                    </ul>
                </div>
                <div class='col-sm-6'>
                    <canvas id="myChart"></canvas>
                </div>
            </div>
        </div>

        <a href="{% url 'polls:detail' question.id %}" class="btn btn-dark" style="color:white;">Vote again</a>
    </div>

{% endblock %}